// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnWrapper': string;
  'buttons': string;
  'header': string;
}
export const cssExports: CssExports;
export default cssExports;
