// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beta': string;
  'container': string;
  'libInfo': string;
  'result': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
