// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'baseLineHeight': string;
  'light': string;
  'noLineHeight': string;
  'shortcut': string;
}
export const cssExports: CssExports;
export default cssExports;
