// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formGroup': string;
  'isCheckbox': string;
  'labelBtn': string;
  'moreInfo': string;
  'requiredField': string;
}
export const cssExports: CssExports;
export default cssExports;
