// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hideDismiss': string;
  'toaster': string;
}
export const cssExports: CssExports;
export default cssExports;
