// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action_button': string;
  'action_disabled': string;
  'active': string;
  'container': string;
  'fullsize': string;
  'imagePreview': string;
  'infoTooltip': string;
  'item': string;
  'itemList': string;
  'itemListSelected': string;
  'label': string;
  'markdownRenderer': string;
  'right': string;
  'rightButtons': string;
  'searchBar': string;
  'sidePanel': string;
  'sidePanel_hidden': string;
  'sidePanel_section': string;
  'splashScreen': string;
  'toolbar': string;
  'yOverflowScroll': string;
}
export const cssExports: CssExports;
export default cssExports;
