// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorMessage': string;
  'label': string;
  'labelError': string;
}
export const cssExports: CssExports;
export default cssExports;
