// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapseBtn': string;
  'collapsibleContainer': string;
  'subSection': string;
}
export const cssExports: CssExports;
export default cssExports;
