// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'icon': string;
  'success': string;
}
export const cssExports: CssExports;
export default cssExports;
