// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'delete': string;
  'moreBtn': string;
  'moreBtnDots': string;
  'moreMenu': string;
  'moreMenuItem': string;
  'noHover': string;
}
export const cssExports: CssExports;
export default cssExports;
