// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'section': string;
  'sectionTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
