// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'borderTop': string;
  'deleteFile': string;
  'errorIcon': string;
  'fieldWrapperHeader': string;
  'groupLabel': string;
  'label': string;
  'labelWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
